#!/bin/bash

# avoiding the conflict with possible host proxy or vpn
export NO_PROXY=

# GET Method
curl -i -v --proxy http://localhost:8080 http://localhost:5000/

# POST Method
curl -i -v --proxy http://localhost:8080 -X POST http://localhost:5000/ \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -d "key1=value1&key2=value2"

# PUT Method
curl -i -v --proxy http://localhost:8080 -X PUT http://localhost:5000/ \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -d "key1=new_value1&key2=new_value2"

# DELETE Method
curl -i -v --proxy http://localhost:8080 -X DELETE http://localhost:5000/ \
     -H "Authorization: Bearer token" \
     -H "Custom-Header: CustomValue"
